// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serverchat.proto

package com.example.grpc.chat.server;

public interface ChatMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.ChatMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_name = 1;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string user_name = 1;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string message_text = 2;</code>
   * @return The messageText.
   */
  java.lang.String getMessageText();
  /**
   * <code>string message_text = 2;</code>
   * @return The bytes for messageText.
   */
  com.google.protobuf.ByteString
      getMessageTextBytes();
}
