// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serverchat.proto

package com.example.grpc.chat.server;

public interface ChatMessageFromServerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.ChatMessageFromServer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.chat.ChatMessage message = 1;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>.chat.ChatMessage message = 1;</code>
   * @return The message.
   */
  com.example.grpc.chat.server.ChatMessage getMessage();
  /**
   * <code>.chat.ChatMessage message = 1;</code>
   */
  com.example.grpc.chat.server.ChatMessageOrBuilder getMessageOrBuilder();
}
