# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbank.proto\"R\n\x16\x43onvertCurrencyRequest\x12\x14\n\x0c\x63urrencyFrom\x18\x01 \x01(\t\x12\x12\n\ncurrencyTo\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\"c\n\x17\x43onvertCurrencyResponse\x12\x14\n\x0c\x63urrencyFrom\x18\x01 \x01(\t\x12\x12\n\ncurrencyTo\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x0e\n\x06result\x18\x04 \x01(\x01\x32\xa8\x02\n\x0b\x42\x61nkService\x12<\n\x07\x63onvert\x12\x17.ConvertCurrencyRequest\x1a\x18.ConvertCurrencyResponse\x12H\n\x11getCurrencyStream\x12\x17.ConvertCurrencyRequest\x1a\x18.ConvertCurrencyResponse0\x01\x12\x44\n\rperformStream\x12\x17.ConvertCurrencyRequest\x1a\x18.ConvertCurrencyResponse(\x01\x12K\n\x12\x66ullCurrencyStream\x12\x17.ConvertCurrencyRequest\x1a\x18.ConvertCurrencyResponse(\x01\x30\x01\x42\x10\n\x0emiaad.sd.stubsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bank_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016miaad.sd.stubs'
  _CONVERTCURRENCYREQUEST._serialized_start=14
  _CONVERTCURRENCYREQUEST._serialized_end=96
  _CONVERTCURRENCYRESPONSE._serialized_start=98
  _CONVERTCURRENCYRESPONSE._serialized_end=197
  _BANKSERVICE._serialized_start=200
  _BANKSERVICE._serialized_end=496
# @@protoc_insertion_point(module_scope)
